name: "sample custom action"
description: "github actions 실습-숫자 증가시키는 액션"
author: "OhDaky"
inputs:
  number: # change this
    required: true
    description: "숫자 증가"
    default: "0"
outputs:
  value:
    default: "증가된 숫자"
runs:
  using: "node16"
  main: "dist/index.js"
